### PR TITLE
Upgrade packages and fix it

### LINKED ISSUE #200: Cannot read property 'head' of undefined
**Describe the bug**

During a run of the Github Actions I get the following:

```
Run stoplightio/spectral-action@v0.6.1
  with:
    file_glob: reference/v2/Index.yaml
    repo_token: ***
    event_name: pull_request
/usr/bin/docker run --name c27d31e4036e1dba5842deb4ae1a78b0ffbbb1_d82818 --label c27d31 --workdir /github/workspace --rm -e INPUT_FILE_GLOB -e INPUT_SPECTRAL_RULESET -e INPUT_REPO_TOKEN -e INPUT_EVENT_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/captains-log/captains-log":"/github/workspace" c27d31:e4036e1dba5842deb4ae1a78b0ffbbb1
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'head' of undefined
    at extractSha (/action/dist/octokit.js:37:47)
    at /action/dist/octokit.js:53:34
    at /action/node_modules/fp-ts-contrib/lib/Do.js:31:96
    at Object.chain (/action/node_modules/fp-ts/lib/Either.js:474:57)
    at DoClass.bindL (/action/node_modules/fp-ts-contrib/lib/Do.js:31:43)
    at Object.exports.getRepositoryInfoFromEvent (/action/dist/octokit.js:53:6)
    at /action/dist/index.js:83:243
    at /action/node_modules/fp-ts/lib/EitherT.js:21:159
    at /action/node_modules/fp-ts/lib/Task.js:114:91
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

main.yml
```
name: Run Spectral Linter on Pull Requests

on:
  - pull_request

jobs:
  build:
    name: Run Spectral Linter
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.6.1
        with:
          file_glob: 'reference/v2/Index.yaml'
```

**Additional context**
This also results in a 'pass' for the Github 'Check' which is surprising, I would expect an error on the command output to exit with 0 and show this as a failure.
image

### LINKED ISSUE #221: No relevant error information
**Summary**
Show the exact error that caused the action failure

**Example**
All it says is '1 issue detected':
image

When I run the linter locally, I get `error  oas3-schema  'requestBody' property should have required property '$ref'`. This is an issue in of itself that I documented here: https://github.com/stoplightio/spectral/issues/1072#issuecomment-636482005.

### LINKED ISSUE #325: Bump spectral to 5.5
## Summary

Bump spectral to 5.5

### LINKED ISSUE #334: Error when linting produces more than 50 annotations
## Describe the bug

Running this action against a large OAS yaml file, and it gets the following error:

```
No more than 50 items are allowed; 77 were supplied.
```

It would seem that this is a result of the limit on Annotations to be added in a single API request, as per https://developer.github.com/v3/checks/runs/

> The Checks API limits the number of annotations to a maximum of 50 per API request. To create more than 50 annotations, you have to make multiple requests to the Update a check run endpoint. Each time you update the check run, annotations are appended to the list of annotations that already exist for the check run. For details about how you can view annotations on GitHub, see "About status checks".

## To Reproduce

Setup this action to run for every new pull request.
Create a new yaml file with more than 50 linting errors, and create a new pull request for it.

## Expected behavior

This action should post back annotations to the action for every linting error, regardless of the count.

### PR DESCRIPTION
**Pull request by XVincentX**
Closes #325 
Closes #200 
Closes #221
Closes #334

### CODE REVIEW

File: src/octokit.ts [hunk 1]
```diff
@@ -44,15 +52,15 @@ export interface IRepositoryInfo {
 const extractSha = (eventName: string, event: any): E.Either<Error, string> => {
```
Comment (grische) [inline src/octokit.ts:52]: @XVincentX Why are you using `event: any` and not `event: Event` here? 
Is `event.pull_request` ever valid?

Comment (XVincentX) [reply src/octokit.ts:52]: Because apparently the definitions are wrong; I'm gonna try to take another look into but we'd need a decoder for this instead of relying on the typings.
